# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

with open('key.txt', 'r') as file:
  data = file.readlines()
  username = data[0].strip()
  password = data[1].strip()


class TestDefaultSuite():
  def setup_method(self, method):
    self.driver = webdriver.Edge()
    self.vars = {}

  def teardown_method(self, method):
    self.driver.quit()

  def test_testing1(self):
    self.driver.get("https://elearning.ntu.edu.vn/")
    self.driver.set_window_size(1278, 672)
    self.driver.find_element(By.LINK_TEXT, "Log in").click()
    self.driver.find_element(By.ID, "username").send_keys(username)
    self.driver.find_element(By.ID, "password").send_keys(password)
    self.driver.find_element(By.ID, "loginbtn").click()
    self.driver.find_element(By.CSS_SELECTOR, ".usertext").click()
    self.driver.find_element(By.ID, "actionmenuaction-6").click()

    with open('key_success.txt', 'w') as file:
      file.write("Test case passed successfully!")
